# ---------------------------------------------------------------------------
# SpeexDSP integration (BSD-licensed, no upstream CMakeLists).
#
# Builds a small static library `speexdsp-core` containing only the sources
# required by SpeexDSP's preprocess (denoise / VAD / AGC) and jitter buffer
# APIs. The submodule is read-only; we list the files we want explicitly
# rather than globbing, so test programs, examples, resampler, and
# documentation sources are never linked.
#
# Sources included (intentionally):
#   - preprocess.c     (speex_preprocess state + run; VAD probability, denoise)
#   - jitter.c         (Jitter buffer helper)
#   - buffer.c         (Speex circular buffer helpers used by preprocess/jitter)
#   - fftwrap.c        (FFT wrapper used by preprocess's spectral subtraction)
#   - filterbank.c     (analysis filterbank used by preprocess)
#   - kiss_fft.c       (kiss FFT core; required by fftwrap / filterbank)
#   - kiss_fftr.c      (real FFT used by filterbank)
#   - smallft.c        (smallft fallback used by some preprocess paths)
#   - mdf.c            (echo canceller helper included only to satisfy the
#                       preprocess residual-echo symbol `speex_echo_get_residual`;
#                       not used to expose acoustic echo cancellation to the
#                       rest of the project)
#
# Deliberately excluded:
#   - resample.c       (we already have r8brain for resampling)
#   - scal.c           (speex scal quantiser - not needed)
#   - test*.c          (test programs containing main())
#   - echo_diagnostic.m (Matlab diagnostic, not C)
# ---------------------------------------------------------------------------

set(SPEEXDSP_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/external/speexdsp")
set(SPEEXDSP_SRC_DIR "${SPEEXDSP_ROOT}/libspeexdsp")
set(SPEEXDSP_INC_DIR "${SPEEXDSP_ROOT}/include")
set(SPEEXDSP_CONFIG_TYPES_H "${CMAKE_CURRENT_BINARY_DIR}/speexdsp/speexdsp_config_types.h")
set(SPEEXDSP_CONFIG_TYPES_H_DIR "${CMAKE_CURRENT_BINARY_DIR}/speexdsp")

# speexdsp_types.h includes <speex/speexdsp_config_types.h> as a fallback
# type provider. Upstream generates it from a .in template via autotools.
# We don't need any fixed-point / debug configuration (preprocess/jitter
# use floating-point internally), so write a minimal C99-compliant shim
# that maps the spx_* typedefs to stdint equivalents.
file(WRITE "${SPEEXDSP_CONFIG_TYPES_H}"
     "/* Auto-generated by cmake/speexdsp.cmake - do not edit. */\n"
     "#ifndef SPEEXDSP_CONFIG_TYPES_H\n"
     "#define SPEEXDSP_CONFIG_TYPES_H\n"
     "#include <stdint.h>\n"
     "typedef int16_t spx_int16_t;\n"
     "typedef uint16_t spx_uint16_t;\n"
     "typedef int32_t spx_int32_t;\n"
     "typedef uint32_t spx_uint32_t;\n"
     "#endif\n")

add_library(speexdsp-core STATIC
    "${SPEEXDSP_SRC_DIR}/preprocess.c"
    "${SPEEXDSP_SRC_DIR}/jitter.c"
    "${SPEEXDSP_SRC_DIR}/buffer.c"
    "${SPEEXDSP_SRC_DIR}/fftwrap.c"
    "${SPEEXDSP_SRC_DIR}/filterbank.c"
    "${SPEEXDSP_SRC_DIR}/kiss_fft.c"
    "${SPEEXDSP_SRC_DIR}/kiss_fftr.c"
    "${SPEEXDSP_SRC_DIR}/smallft.c"
    # mdf.c provides `speex_echo_get_residual`, which preprocess.c calls
    # unconditionally inside speex_preprocess_run() whenever a SpeexEchoState
    # is attached via SPEEX_PREPROCESS_SET_ECHO_STATE. We do not call any
    # other symbol from mdf.c, so acoustic echo cancellation stays internal
    # to the static lib and is not exposed via the speexdsp-core PUBLIC API.
    "${SPEEXDSP_SRC_DIR}/mdf.c"
)

target_include_directories(speexdsp-core PUBLIC
    "${SPEEXDSP_INC_DIR}"
    "${SPEEXDSP_CONFIG_TYPES_H_DIR}"
)

# SpeexDSP's arch.h requires exactly one of FIXED_POINT / FLOATING_POINT to be
# defined for every translation unit. We deliberately build the floating-point
# variant (matches our host signal path; r8brain / EVS-float are float-based).
# Marked PRIVATE because the choice is an internal build detail of
# speexdsp-core; downstream targets only need the public preprocess / jitter
# API surface. PUBLIC (not INTERFACE) because the sources are built inside
# this target.
target_compile_definitions(speexdsp-core PRIVATE FLOATING_POINT)

# Upstream autotools generates EXPORT via AC_DEFINE:
#   - On GCC it expands to __attribute__((visibility("default"))) for the
#     shared-library build; the static-library branch leaves it empty.
#   - On non-GCC (MSVC) it is left empty unconditionally.
# Only resample.c has a built-in #ifndef EXPORT fallback; every other
# source (preprocess.c, jitter.c, buffer.c, ...) emits `EXPORT` token
# directly. Define it to nothing here so MSVC / our static build matches
# upstream's static-library behaviour.
target_compile_definitions(speexdsp-core PRIVATE EXPORT=)

# fftwrap.c (used by preprocess.c) needs exactly one of USE_KISS_FFT /
# USE_SMALLFT selected at compile time. Upstream's autotools picks one
# (sometimes both) via BUILD_KISS_FFT / BUILD_SMALLFT AM_CONDITIONALs;
# we ship both kiss_fft*.c and smallft.c above, so we tell fftwrap to
# use the kiss path. Define it to nothing so it matches the upstream
# empty-token convention (fftwrap uses `#ifdef USE_KISS_FFT`, not the
# value).
target_compile_definitions(speexdsp-core PRIVATE USE_KISS_FFT)

if(MSVC)
    target_compile_definitions(speexdsp-core PRIVATE _CRT_SECURE_NO_WARNINGS)
endif()